export const SET_INITIAL_APP_DATA = "SET_INITIAL_APP_DATA"
export const FETCH_ALL_DECKS = "FETCH_ALL_DECKS"
export const FETCH_DECK_DETAILS = "FETCH_DECK_DETAILS"
export const NEW_DECK_ADDED = "NEW_DECK_ADDED"
